added clean exit default cases

diff --git a/dockergui b/dockergui
--- a/dockergui
+++ b/dockergui
@@ -27,6 +27,7 @@ if command -v ratpoison; then
 	sleep 1
 	ratpoison -d :$DNum &
 else # Use the default x window manager installed based on lsb_release id
+
 	DISPLAY=:$DNum
 	distro_id=$(lsb_release -i | awk '{print($3)}')
 
@@ -37,6 +38,10 @@ else # Use the default x window manager installed based on lsb_release id
 			startplasma-x11 &
 		elif [ "${XDG_SESSION_DESKTOP}" == "GNOME" ]; then
 			mutter &
+		else
+			printf "%s\n" "Could not find a suitable Window Manager"
+			exit 1
+
 		fi
  
 	fi
@@ -52,6 +57,9 @@ if command -v docker; then
 	
 elif command -v podman; then 
 	engine_of_choice="podman"
+else
+	printf "%s\n" "Docker/Podman are not installed!"
+	exit 1
 fi
 
 # then run the detected container engine
